// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQy_wBqBr_4QUT4gxhWvV4Q_0aOhPlOC0',
    appId: '1:420193807916:web:ee1c7d429570a3d1246b89',
    messagingSenderId: '420193807916',
    projectId: 'word-rush-game',
    authDomain: 'word-rush-game.firebaseapp.com',
    storageBucket: 'word-rush-game.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnyeStOh9Yu5TzjUhPwYYaxqJwq21y8nc',
    appId: '1:420193807916:android:e8029b996a371950246b89',
    messagingSenderId: '420193807916',
    projectId: 'word-rush-game',
    storageBucket: 'word-rush-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIKwwsUwbC2XKpERV-38mQbBG7u4vx5UQ',
    appId: '1:420193807916:ios:cf57779472ab77d2246b89',
    messagingSenderId: '420193807916',
    projectId: 'word-rush-game',
    storageBucket: 'word-rush-game.appspot.com',
    iosBundleId: 'com.bumblestudio.wordRush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIKwwsUwbC2XKpERV-38mQbBG7u4vx5UQ',
    appId: '1:420193807916:ios:a03bd48f2d28bf5a246b89',
    messagingSenderId: '420193807916',
    projectId: 'word-rush-game',
    storageBucket: 'word-rush-game.appspot.com',
    iosBundleId: 'com.bumblestudio.wordRush.RunnerTests',
  );
}
